### ISSUE TITLE
Support for Rubeus 1.5.0

### ISSUE THREAD

**Issue by mgeeky** [xan7r/Misc#1]
Hi! Thanks for the magnificent `SaveTickets.cna` CS script! I really like it :-) 

Just noticed the script is not really able to capture output tickets from Rubeus 1.5+ versions (they added `/nowrap` switch as well - could be useful to extract tickets from within a script). 

Do you think you could find some spare time to add a support for upgraded Rubeus? 

Thanks!

Cheers,
M.

**Comment by matxr14** [comment]
Where is the punch line? This isn't funny. 😢.

**Comment by xan7r** [comment]
Hi mgeeky!  I'm glad you found my script useful.

Thanks for the heads up about Rubeus 1.5.0 incompatibility, looks like they made minor changes to some of the output patterns I was using to parse tickets.  I'll work on adding compatibility support soon.

**Comment by xan7r** [comment]
Looks like they made changes to the output of the dump and monitor modules.  I've updated the SaveTickets.cna script so that it should work with Rubeus 1.5.0.  

Also, I kept a copy of the old script as SaveTickets-v1.4.cna in case you want to use legacy versions of Rubeus.

Thanks again for giving me the heads up about this.  Let me know if you find any other issues.
